### PR TITLE
fix(#23): missing target membership reference

### LINKED ISSUE #23: Crash when generating iOS plugin
### Environment

node version: 16.7.1

### Is used with npx or as a local dependency?

- [X] npx
- [ ] local dependency

### Affected commands

- [ ] android
- [X] ios

### Current behavior

App crashes after generating plugin and running the app

https://github.com/mrousavy/react-native-vision-camera/issues/1307
https://github.com/mrousavy/react-native-vision-camera/issues/1295

### Expected behavior

App does not crash

### Reproduction repository link

I already reproduced it

### PR DESCRIPTION
**Pull request by mateusz1913**
This pull request resolves #23 

**Description**

fix missing target membership reference

### CODE REVIEW

File: generateIOS.rb [hunk 1]
```diff
@@ -31,42 +31,43 @@
...
-    target.build_configurations.each do |config|
-      if config.build_settings['SWIFT_OBJC_BRIDGING_HEADER'] == nil
-        # Create default bridging header if needed and link it to build settings
-        if File.exist?(default_bridging_header_path) == false
-          bridging_header_file = File.new(default_bridging_header_path, 'w+')
-          File.write(default_bridging_header_path, bridging_headers, mode: 'a')
-          bridging_header_file.close
-          is_bridging_header_created = true
-          puts "Created #{default_bridging_header_filename}"
+    if target.product_type == ("com.apple.product-type.application" || "com.apple.product-type.library.static")
```
Comment (wodin) [inline generateIOS.rb:34]: This looks wrong?
```ruby
$ irb
irb(main):001:0> "com.apple.product-type.application" || "com.apple.product-type
.library.static"
=> "com.apple.product-type.application"
```
So unless I'm missing something, that line seems to be equivalent to:
```ruby
    if target.product_type == "com.apple.product-type.application"
```
I think what you want instead is:
```ruby
if ["com.apple.product-type.application", "com.apple.product-type.library.static"].include? target.product_type
```

Testing:
```ruby
$ irb
irb(main):001:0> product_type = "com.apple.product-type.application"
=> "com.apple.product-type.application"
irb(main):002:0> ["com.apple.product-type.application", "com.apple.product-type.library.static"].include? product_type
=> true
irb(main):003:0> product_type = "com.apple.product-type.library.static"
=> "com.apple.product-type.library.static"
irb(main):004:0> ["com.apple.product-type.application", "com.apple.product-type.library.static"].include? product_type
=> true
irb(main):005:0> product_type = "test"
=> "test"
irb(main):006:0> ["com.apple.product-type.application", "com.apple.product-type.library.static"].include? product_type
=> false
irb(main):007:0> 
```

Comment (wodin) [reply generateIOS.rb:34]: I'm not quite sure what you're asking :)

The following:
```ruby
    if target.product_type == ("com.apple.product-type.application" || "com.apple.product-type.library.static")
```
is equivalent to:
```ruby
    if target.product_type == "com.apple.product-type.application"
```
because `"string1" || "string2"` evaluates to `"string1"`.

The following:
```ruby
if ["com.apple.product-type.application", "com.apple.product-type.library.static"].include? target.product_type
```
means: "If target.product_type is equal to either of those two strings, then..."
i.e. "Does this array include (contain) target.product_type?"

Comment (wodin) [reply generateIOS.rb:34]: @mateusz1913 I assume the intention of that line is to say 'If target.product_type is "com.apple.product-type.application" or "com.apple.product-type.library.static" then do the following'.

What it is actually doing is 'If target.product_type is "com.apple.product-type.application" then do the following'.

To get the first meaning you should do:
```ruby
if list_of_possible_values.include?(target.product_type)
```

This is like the following Python code:
```python
if target.product_type in list_of_possible_values
```
